apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: flask-app-ns
spec:
  type: ClusterIP
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080